// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: use-readonly-types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FieldMask } from "./google/protobuf/field_mask";
import { ListValue, Struct } from "./google/protobuf/struct";

export const protobufPackage = "";

export interface Entity {
  readonly intVal: number;
  readonly stringVal: string;
  readonly intArray: readonly number[];
  readonly stringArray: readonly string[];
  readonly subEntity: SubEntity | undefined;
  readonly subEntityArray: readonly SubEntity[];
  readonly optionalIntVal?: number | undefined;
  readonly fieldMask: readonly string[] | undefined;
  readonly listValue: ReadonlyArray<any> | undefined;
  readonly structValue: { readonly [key: string]: any } | undefined;
  readonly oneOfValue?: { readonly $case: "theStringValue"; readonly theStringValue: string } | {
    readonly $case: "theIntValue";
    readonly theIntValue: number;
  } | undefined;
}

export interface SubEntity {
  readonly subVal: number;
}

function createBaseEntity(): Entity {
  return {
    intVal: 0,
    stringVal: "",
    intArray: [],
    stringArray: [],
    subEntity: undefined,
    subEntityArray: [],
    optionalIntVal: undefined,
    fieldMask: undefined,
    listValue: undefined,
    structValue: undefined,
    oneOfValue: undefined,
  };
}

export const Entity: MessageFns<Entity> = {
  encode(message: Entity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.intVal !== 0) {
      writer.uint32(8).int32(message.intVal);
    }
    if (message.stringVal !== "") {
      writer.uint32(18).string(message.stringVal);
    }
    writer.uint32(26).fork();
    for (const v of message.intArray) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.stringArray) {
      writer.uint32(34).string(v!);
    }
    if (message.subEntity !== undefined) {
      SubEntity.encode(message.subEntity, writer.uint32(42).fork()).join();
    }
    for (const v of message.subEntityArray) {
      SubEntity.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.optionalIntVal !== undefined) {
      writer.uint32(56).int32(message.optionalIntVal);
    }
    if (message.fieldMask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.fieldMask), writer.uint32(66).fork()).join();
    }
    if (message.listValue !== undefined) {
      ListValue.encode(ListValue.wrap(message.listValue), writer.uint32(74).fork()).join();
    }
    if (message.structValue !== undefined) {
      Struct.encode(Struct.wrap(message.structValue), writer.uint32(82).fork()).join();
    }
    switch (message.oneOfValue?.$case) {
      case "theStringValue":
        writer.uint32(90).string(message.oneOfValue.theStringValue);
        break;
      case "theIntValue":
        writer.uint32(96).int32(message.oneOfValue.theIntValue);
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Entity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntity() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.intVal = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stringVal = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.intArray.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.intArray.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stringArray.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.subEntity = SubEntity.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.subEntityArray.push(SubEntity.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.optionalIntVal = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fieldMask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.listValue = ListValue.unwrap(ListValue.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.structValue = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.oneOfValue = { $case: "theStringValue", theStringValue: reader.string() };
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.oneOfValue = { $case: "theIntValue", theIntValue: reader.int32() };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Entity {
    return {
      intVal: isSet(object.intVal) ? globalThis.Number(object.intVal) : 0,
      stringVal: isSet(object.stringVal) ? globalThis.String(object.stringVal) : "",
      intArray: globalThis.Array.isArray(object?.intArray) ? object.intArray.map((e: any) => globalThis.Number(e)) : [],
      stringArray: globalThis.Array.isArray(object?.stringArray)
        ? object.stringArray.map((e: any) => globalThis.String(e))
        : [],
      subEntity: isSet(object.subEntity) ? SubEntity.fromJSON(object.subEntity) : undefined,
      subEntityArray: globalThis.Array.isArray(object?.subEntityArray)
        ? object.subEntityArray.map((e: any) => SubEntity.fromJSON(e))
        : [],
      optionalIntVal: isSet(object.optionalIntVal) ? globalThis.Number(object.optionalIntVal) : undefined,
      fieldMask: isSet(object.fieldMask) ? FieldMask.unwrap(FieldMask.fromJSON(object.fieldMask)) : undefined,
      listValue: globalThis.Array.isArray(object.listValue) ? [...object.listValue] : undefined,
      structValue: isObject(object.structValue) ? object.structValue : undefined,
      oneOfValue: isSet(object.theStringValue)
        ? { $case: "theStringValue", theStringValue: globalThis.String(object.theStringValue) }
        : isSet(object.theIntValue)
        ? { $case: "theIntValue", theIntValue: globalThis.Number(object.theIntValue) }
        : undefined,
    };
  },

  toJSON(message: Entity): unknown {
    const obj: any = {};
    if (message.intVal !== 0) {
      obj.intVal = Math.round(message.intVal);
    }
    if (message.stringVal !== "") {
      obj.stringVal = message.stringVal;
    }
    if (message.intArray?.length) {
      obj.intArray = message.intArray.map((e) => Math.round(e));
    }
    if (message.stringArray?.length) {
      obj.stringArray = message.stringArray;
    }
    if (message.subEntity !== undefined) {
      obj.subEntity = SubEntity.toJSON(message.subEntity);
    }
    if (message.subEntityArray?.length) {
      obj.subEntityArray = message.subEntityArray.map((e) => SubEntity.toJSON(e));
    }
    if (message.optionalIntVal !== undefined) {
      obj.optionalIntVal = Math.round(message.optionalIntVal);
    }
    if (message.fieldMask !== undefined) {
      obj.fieldMask = FieldMask.toJSON(FieldMask.wrap(message.fieldMask));
    }
    if (message.listValue !== undefined) {
      obj.listValue = message.listValue;
    }
    if (message.structValue !== undefined) {
      obj.structValue = message.structValue;
    }
    if (message.oneOfValue?.$case === "theStringValue") {
      obj.theStringValue = message.oneOfValue.theStringValue;
    } else if (message.oneOfValue?.$case === "theIntValue") {
      obj.theIntValue = Math.round(message.oneOfValue.theIntValue);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Entity>, I>>(base?: I): Entity {
    return Entity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Entity>, I>>(object: I): Entity {
    const message = createBaseEntity() as any;
    message.intVal = object.intVal ?? 0;
    message.stringVal = object.stringVal ?? "";
    message.intArray = object.intArray?.map((e) => e) || [];
    message.stringArray = object.stringArray?.map((e) => e) || [];
    message.subEntity = (object.subEntity !== undefined && object.subEntity !== null)
      ? SubEntity.fromPartial(object.subEntity)
      : undefined;
    message.subEntityArray = object.subEntityArray?.map((e) => SubEntity.fromPartial(e)) || [];
    message.optionalIntVal = object.optionalIntVal ?? undefined;
    message.fieldMask = object.fieldMask ?? undefined;
    message.listValue = object.listValue ?? undefined;
    message.structValue = object.structValue ?? undefined;
    if (
      object.oneOfValue?.$case === "theStringValue" &&
      object.oneOfValue?.theStringValue !== undefined &&
      object.oneOfValue?.theStringValue !== null
    ) {
      message.oneOfValue = { $case: "theStringValue", theStringValue: object.oneOfValue.theStringValue };
    } else if (
      object.oneOfValue?.$case === "theIntValue" &&
      object.oneOfValue?.theIntValue !== undefined &&
      object.oneOfValue?.theIntValue !== null
    ) {
      message.oneOfValue = { $case: "theIntValue", theIntValue: object.oneOfValue.theIntValue };
    }
    return message;
  },
};

function createBaseSubEntity(): SubEntity {
  return { subVal: 0 };
}

export const SubEntity: MessageFns<SubEntity> = {
  encode(message: SubEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subVal !== 0) {
      writer.uint32(8).int32(message.subVal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubEntity() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.subVal = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubEntity {
    return { subVal: isSet(object.subVal) ? globalThis.Number(object.subVal) : 0 };
  },

  toJSON(message: SubEntity): unknown {
    const obj: any = {};
    if (message.subVal !== 0) {
      obj.subVal = Math.round(message.subVal);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubEntity>, I>>(base?: I): SubEntity {
    return SubEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubEntity>, I>>(object: I): SubEntity {
    const message = createBaseSubEntity() as any;
    message.subVal = object.subVal ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { readonly $case: string }
    ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
