// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: simple.proto

/* eslint-disable */

export const protobufPackage = "";

export interface GetMessageRequest {
  messageId: string;
}

export interface GetMessageResponse {
  message: string;
}

export interface CreateMessageRequest {
  messageId: string;
  /** mapped to the body */
  message: string;
}

export interface CreateMessageResponse {
}

export const Messaging = {
  getMessage: {
    path: "/v1/messages/{message_id}",
    method: "get",
    request: undefined as GetMessageRequest | undefined,
    response: undefined as GetMessageResponse | undefined,
  },

  createMessage: {
    path: "/v1/messages/{message_id}",
    method: "post",
    body: "message",
    request: undefined as CreateMessageRequest | undefined,
    response: undefined as CreateMessageResponse | undefined,
  },

  updateMessage: {
    path: "/v1/messages/{message_id}",
    method: "post",
    body: "*",
    request: undefined as CreateMessageRequest | undefined,
    response: undefined as CreateMessageResponse | undefined,
  },
};
