nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.3.0.cjs
