// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: use-json-name-struct.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ListValue, Struct, Value } from "./google/protobuf/struct";

export const protobufPackage = "json_name_struct";

export interface Holder {
  value: any | undefined;
  struct: { [key: string]: any } | undefined;
  list: Array<any> | undefined;
}

function createBaseHolder(): Holder {
  return { value: undefined, struct: undefined, list: undefined };
}

export const Holder: MessageFns<Holder> = {
  encode(message: Holder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== undefined) {
      Value.encode(Value.wrap(message.value), writer.uint32(10).fork()).join();
    }
    if (message.struct !== undefined) {
      Struct.encode(Struct.wrap(message.struct), writer.uint32(18).fork()).join();
    }
    if (message.list !== undefined) {
      ListValue.encode(ListValue.wrap(message.list), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Holder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHolder();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.value = Value.unwrap(Value.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.struct = Struct.unwrap(Struct.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.list = ListValue.unwrap(ListValue.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Holder {
    return {
      value: isSet(object?.value) ? object.value : undefined,
      struct: isObject(object.struct) ? object.struct : undefined,
      list: globalThis.Array.isArray(object.list) ? [...object.list] : undefined,
    };
  },

  toJSON(message: Holder): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    if (message.struct !== undefined) {
      obj.struct = message.struct;
    }
    if (message.list !== undefined) {
      obj.list = message.list;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Holder>, I>>(base?: I): Holder {
    return Holder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Holder>, I>>(object: I): Holder {
    const message = createBaseHolder();
    message.value = object.value ?? undefined;
    message.struct = object.struct ?? undefined;
    message.list = object.list ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
