// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.173.0
//   protoc               v3.19.1
// source: decode.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Encode {
  encode: string;
}

export const Encode = {
  fromJSON(object: any): Encode {
    return { encode: isSet(object.encode) ? globalThis.String(object.encode) : "" };
  },
};

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
