// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.173.0
//   protoc               v3.19.1
// source: use-json-wire-format.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Todo {
  id?: string | undefined;
  timestamp?: string | undefined;
  duration?: string | undefined;
  updateMask?: string | undefined;
}
