// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: google/protobuf/struct.proto

/* eslint-disable */
import { wrappers } from "protobufjs";

export const protobufPackage = "google.protobuf";

export enum NullValue {
  NULL_VALUE = 0,
  UNRECOGNIZED = -1,
}

export interface Struct {
  fields: { [key: string]: any | undefined };
}

export interface Struct_FieldsEntry {
  key: string;
  value: any | undefined;
}

export interface Value {
  nullValue?: NullValue | undefined;
  numberValue?: number | undefined;
  stringValue?: string | undefined;
  boolValue?: boolean | undefined;
  structValue?: { [key: string]: any } | undefined;
  listValue?: Array<any> | undefined;
}

export interface ListValue {
  values: any[];
}

export const GOOGLE_PROTOBUF_PACKAGE_NAME = "google.protobuf";

function createBaseStruct(): Struct {
  return { fields: {} };
}

export const Struct: MessageFns<Struct> & StructWrapperFns = {
  wrap(object: { [key: string]: any } | undefined): Struct {
    const struct = createBaseStruct();

    if (object !== undefined) {
      for (const key of globalThis.Object.keys(object)) {
        struct.fields[key] = Value.wrap(object[key]);
      }
    }
    return struct;
  },

  unwrap(message: Struct): { [key: string]: any } {
    const object: { [key: string]: any } = {};
    if (message.fields) {
      for (const key of globalThis.Object.keys(message.fields)) {
        object[key] = Value.unwrap(message.fields[key]);
      }
    }
    return object;
  },
};

function createBaseValue(): Value {
  return {};
}

export const Value: MessageFns<Value> & AnyValueWrapperFns = {
  wrap(value: any): Value {
    const result = {} as any;
    if (value === null) {
      result.nullValue = NullValue.NULL_VALUE;
    } else if (typeof value === "boolean") {
      result.boolValue = value;
    } else if (typeof value === "number") {
      result.numberValue = value;
    } else if (typeof value === "string") {
      result.stringValue = value;
    } else if (globalThis.Array.isArray(value)) {
      result.listValue = ListValue.wrap(value);
    } else if (typeof value === "object") {
      result.structValue = Struct.wrap(value);
    } else if (typeof value !== "undefined") {
      throw new globalThis.Error("Unsupported any value type: " + typeof value);
    }
    return result;
  },

  unwrap(message: any): string | number | boolean | Object | null | Array<any> | undefined {
    if (message?.hasOwnProperty("stringValue") && message.stringValue !== undefined) {
      return message.stringValue;
    } else if (message?.hasOwnProperty("numberValue") && message?.numberValue !== undefined) {
      return message.numberValue;
    } else if (message?.hasOwnProperty("boolValue") && message?.boolValue !== undefined) {
      return message.boolValue;
    } else if (message?.hasOwnProperty("structValue") && message?.structValue !== undefined) {
      return Struct.unwrap(message.structValue as any);
    } else if (message?.hasOwnProperty("listValue") && message?.listValue !== undefined) {
      return ListValue.unwrap(message.listValue);
    } else if (message?.hasOwnProperty("nullValue") && message?.nullValue !== undefined) {
      return null;
    }
    return undefined;
  },
};

function createBaseListValue(): ListValue {
  return { values: [] };
}

export const ListValue: MessageFns<ListValue> & ListValueWrapperFns = {
  wrap(array: Array<any> | undefined): ListValue {
    const result = createBaseListValue();
    result.values = (array ?? []).map(Value.wrap);
    return result;
  },

  unwrap(message: ListValue): Array<any> {
    if (message?.hasOwnProperty("values") && globalThis.Array.isArray(message.values)) {
      return message.values.map(Value.unwrap);
    } else {
      return message as any;
    }
  },
};

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

export interface MessageFns<T> {
}

export interface StructWrapperFns {
  wrap(object: { [key: string]: any } | undefined): Struct;
  unwrap(message: Struct): { [key: string]: any };
}

export interface AnyValueWrapperFns {
  wrap(value: any): Value;
  unwrap(message: any): string | number | boolean | Object | null | Array<any> | undefined;
}

export interface ListValueWrapperFns {
  wrap(array: Array<any> | undefined): ListValue;
  unwrap(message: ListValue): Array<any>;
}
