// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: google/protobuf/timestamp.proto

/* eslint-disable */

export const protobufPackage = "google.protobuf";

export interface Timestamp {
  seconds: number;
  nanos: number;
}

export const GOOGLE_PROTOBUF_PACKAGE_NAME = "google.protobuf";
