// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.173.0
//   protoc               v3.19.1
// source: only-types-grpc-metadata.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "basic";

export interface GetBasicRequest {
  name: string;
}

export interface GetBasicResponse {
  name: string;
}

export interface BasicService {
  getBasic(request: GetBasicRequest, metadata?: Metadata): Promise<GetBasicResponse>;
}
