// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.173.0
//   protoc               v3.19.1
// source: reservation.proto

/* eslint-disable */
import type { Any } from "./google/protobuf/any";

export const protobufPackage = "event";

export interface Registration {
  eventName: string;
  date: Date | undefined;
  perks: Any | undefined;
}
